// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB4uPGNFw1NDwWc2nTecbYv1032dlliiM',
    appId: '1:996640315076:web:87bcbf2f3b093303425b91',
    messagingSenderId: '996640315076',
    projectId: 'carrot-market-fd142',
    authDomain: 'carrot-market-fd142.firebaseapp.com',
    storageBucket: 'carrot-market-fd142.appspot.com',
    measurementId: 'G-338CSS69GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxprFOi21wOTSDcHJkq2wRZo1Zic1HTvg',
    appId: '1:996640315076:android:50d9ca8423b10808425b91',
    messagingSenderId: '996640315076',
    projectId: 'carrot-market-fd142',
    storageBucket: 'carrot-market-fd142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEEnt3brzCywesq8WFYdYIgkM6k3d4Miw',
    appId: '1:996640315076:ios:bee987768dc2ab2d425b91',
    messagingSenderId: '996640315076',
    projectId: 'carrot-market-fd142',
    storageBucket: 'carrot-market-fd142.appspot.com',
    iosClientId: '996640315076-q3vchgh6m6v28m0ffstfoqurvmf5itf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrotMarket20',
  );
}
